version: '3.9'

services:
  db:
    image: mysql:8
    container_name: tt_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}

volumes:
  file_storage:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${PWD}/file_storage