version: '3.9'

services:
  db:
    image: mysql:8
    container_name: fest_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    networks:
      - fest_network
    healthcheck:
          test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
          timeout: 20s
          retries: 10

  # supertokens:
  #   image: registry.supertokens.io/supertokens/supertokens-mysql:5.0
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   ports:
  #     - 3567:3567
  #   environment:
  #     MYSQL_CONNECTION_URI: mysql://${DB_USER}:${DB_PASSWORD}@db:3306/${DB_NAME}
  #   networks:
  #     - fest_network
  #   restart: unless-stopped
  #   healthcheck:
  #     test: >
  #       bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

networks:
  fest_network:
    driver: bridge

volumes:
  file_storage:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${PWD}/file_storage