version: '3.9'

services:
  db:
    image: mysql:8.0.33
    container_name: fest_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    networks:
      - fest_network
    healthcheck:
          test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
          timeout: 20s
          retries: 10
  
networks:
  fest_network:
    driver: bridge

volumes:
  file_storage:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${PWD}/file_storage