version: '3.9'

services:
  db:
    image: mysql:8
    container_name: keycloak_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${KC_DB_ROOT_PASSWORD}
      - MYSQL_USER=${KC_DB_USERNAME}
      - MYSQL_PASSWORD=${KC_DB_PASSWORD}
      - MYSQL_DATABASE=${KC_DB_NAME}
    networks:
      - fest_network
    healthcheck:
          test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
          timeout: 20s
          retries: 10
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    depends_on:
      db:
        condition: service_healthy
    ports: 
      - 8080:8080
    networks:
      - fest_network
    command: "start-dev"
    restart: unless-stopped
    environment:
      - KC_DB=mysql
      - KC_DB_URL=jdbc:mysql://db:3306/${KC_DB_NAME}
      - KC_DB_USERNAME=${KC_DB_USERNAME}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      # - KC_HOSTNAME=localhost
      # - KC_DB_URL_HOST=127.0.0.1

networks:
  fest_network:
    driver: bridge

volumes:
  file_storage:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${PWD}/file_storage