import "~/styles/globals.css"
import Client from "./client"
import { ReactNode } from "react"


export const metadata = {
  title: "Нян-Фест",
  // description: "Generated by create-t3-app",
}

export default function RootLayout({children}: {children: ReactNode}) {
  return (
    <Client>
      {children}
    </Client>
  )
}
